sequenceDiagram
  participant browser
  participant server
  
  browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
  activate server
  server-->>browser: HTTP status code 302 https://studies.cs.helsinki.fi/exampleapp/notes
  deactivate server

  Note right of browser:  The browser reloads the Notes page. The reload causes three more HTTP requests

  browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
  activate server
  server-->>browser: fetch the style sheet (css) file
  deactivate server

  browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
  activate server
  server-->>browser: fetch the JavaScript code
  deactivate server

  browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
  activate server
  server-->>browser: fetch the raw data of the notes
  deactivate server

  Note right of browser: The network tab also shows the data submitted with the form